version: '3.7'
services:

  mysql:
    image: mysql:5.7
    container_name: reciplease_mysql_3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./instances/mysql:/var/lib/mysql
    restart: always
    stdin_open: true
    tty: true

  ngrok:
    image: wernight/ngrok
    container_name: reciplease_ngrok_4040
    ports:
      - 4040:4040
    environment:
      - NGROK_PROTOCOL=https
      - NGROK_PORT=mysql:3306
      - NGROK_AUTH=${NGROK_AUTH}
    links:
      - mysql
    restart: always
    stdin_open: true
    tty: true
