# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test-ui:
    docker:
      - image: circleci/node

    working_directory: ~/repo/reciplease-ui

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run:
          name: Install node-gyp
          command: yarn global add node-gyp

      - run:
          name: Install dependencies
          command: yarn install --frozen -lockfile

      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run tests with JUnit as reporter
          command: yarn run junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "reciplease-ui/yarn.lock" }}
            - yarn-packages-

      - run: mvn dependency:go-offline

      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "reciplease-ui/yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: mvn test
      - store_artifacts:
          path:  target
      - codecov/upload:
          file: target/my-reports/jacoco.xml
      - run:
          name: Save test results
          command: |
            mkdir -p reports/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} reports/junit/ \;
          when: always
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh $HEROKU_APP $HEROKU_LOGIN $HEROKU_API_KEY
      - run:
          name: Deploy master to Heroku
          command: |
            git push heroku master

workflows:
  version: 2
  build:
    jobs:
      - test-ui
      - build
      - deploy:
          requires:
            - test-ui
            - build
          filters:
            branches:
              only: master