name: Deploy to gcloud

on:
  push:
    branches: [ master ]

env:
  MVN: mvn
  GIT: git
  DOCKER: docker
  GCLOUD: gcloud

jobs:
  jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download dependencies
        run: make init

      - name: Release version
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          make release

      - name: Build with Maven
        run: make build

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v1
        with:
          name: jar-artifacts
          path: |
            dist/target/reciplease-dist.jar
            Dockerfile

      - name: Upload Makefile
        uses: actions/upload-artifact@v1
        with:
          name: Makefile
          path: Makefile
  image:
    needs: jar
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifacts
        uses: actions/download-artifact@v2
        with:
          name: jar-artifacts

      - name: Download Makefile
        uses: actions/download-artifact@v2
        with:
          name: Makefile

      - name: Publish image
        run: make image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          JAR_FILE: reciplease-dist.jar
          DOCKER_TOKEN: ${{ secrets.GCP_SA_KEY }}

  deploy:
    needs: image
    runs-on: ubuntu-latest

    steps:
      - name: Download Makefile
        uses: actions/download-artifact@v2
        with:
          name: Makefile

      - name: Configure gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '299.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: make deploy
        env:
          GCP_REGION: ${{ secrets.GCP_REGION }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
