name: Deploy to gcloud

on:
  push:
    branches: [ main ]

env:
  MVN: mvn
  GIT: git
  DOCKER: docker
  GCLOUD: gcloud
  BASH: bash
  SHELL: bash

jobs:
  waiting:
    runs-on: ubuntu-latest

    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  jar:
    needs: waiting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download dependencies
        run: make init

      - name: Release version
        run: make git-init release

      - name: Build with Maven
        run: make build

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: jar-artifact
          path: build/reciplease-dist.jar

  image:
    needs: jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Download JAR artifacts
        uses: actions/download-artifact@v2
        with:
          name: jar-artifact

      - name: Publish image
        run: make image
        env:
          JAR_FILE: reciplease-dist.jar
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_DOCKER_TOKEN: ${{ secrets.GCP_SA_KEY }}

  deploy:
    needs: image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: make deploy
        env:
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
