name: Deploy to gcloud

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
      - uses: actions/download-artifact@v2
        with:
          name: dist-jar
      - uses: actions/download-artifact@v2
        with:
          name: gcloud-config

      - name: Configure gcloud
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '299.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy app
      - run: gcloud app deploy reciplease-dist.jar --appyaml gcloud-app.yml --stop-previous-version --quiet