name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml')-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload application artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-jar
          path: dist/target/reciplease-dist.jar

      - name: Upload gcloud config
        uses: actions/upload-artifact@v1
        with:
          name: gcloud-config
          path: gcloud-app.yml

      - name: Upload code coverage
        uses: codecov/codecov-action@v1.0.6
        with:
          file:
            - core/target/my-reports/jacoco.xml
            - database/target/my-reports/jacoco.xml
            - web/target/my-reports/jacoco.xml
          fail_ci_if_error: true