name: Testing

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/* ]

env:
  MVN: mvn
  BASH: bash
  SHELL: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Cache maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download dependencies
        run: make init

      - name: Run tests
        run: make test

      - name: Upload code coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            modules/core/target/my-reports/jacoco.xml,
            modules/database/target/my-reports/jacoco.xml,
            modules/web/target/my-reports/jacoco.xml
          fail_ci_if_error: true
